<link href="{{asset('js/bower_components/normalize-css/normalize.css')}}" rel="stylesheet" type="text/css"/>
<link href="{{asset('js/bower_components/bootstrap/dist/css/bootstrap-theme.min.css')}}" rel="stylesheet" type="text/css"/>
<link href="{{asset('js/bower_components/bootstrap/dist/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css"/>
<link href="{{asset('js/bower_components/jquery-ui/jquery-ui.min.css')}}" rel="stylesheet" type="text/css"/>
<link href="{{asset('js/bower_components/carrusel/owl.carousel.css')}}" rel="stylesheet" type="text/css"/>
<link href="{{asset('js/bower_components/carrusel/owl.theme.css')}}" rel="stylesheet" type="text/css"/>
<link href="{{asset('css/web.css')}}" rel="stylesheet" type="text/css"/>
<link href="{{asset('css/web-movil.css')}}" rel="stylesheet" type="text/css"/>
<link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:light&v1' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Open+Sans:light&v1' rel='stylesheet' type='text/css'>
<link href="{{asset('css/detalle.css')}}" rel="stylesheet" type="text/css"/>
<link href="{{asset('css/detalle-movil.css')}}" rel="stylesheet" type="text/css"/>
<link href="{{asset('css/font-awesome.min.css')}}" rel="stylesheet" type="text/css"/>